---
sudo: required

stages:
  - syntax
  - integration
  - name: deploy
    if: branch = master

services:
  - docker

before_install:
  - sudo apt-get update && sudo apt-get install -y openssl

jobs:
  include:
#    - stage: syntax
#      name: "Hadolint"
#      script:
#        - docker run --rm -i hadolint/hadolint < src/main/images/foreman/Dockerfile
#        - docker run --rm -i hadolint/hadolint < src/main/images/puppet/Dockerfile
#    -
#      name: "Shellchecker"
#      script: docker run --rm -v "$(pwd)":/mnt koalaman/shellcheck:stable src/main/images/foreman/*.sh
#    - stage: integration
#      name: "docker-compose"
#      env:
#        - DOCKER_COMPOSE_VERSION=1.23.1
#      before_script:
#        - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#        - sudo chmod +x /usr/local/bin/docker-compose
#      script:
#        - cd examples/docker-compose
#        - sudo docker-compose up -d
#        - sleep 180
#        - cd $TRAVIS_BUILD_DIR
#        - pwd
#        - sudo docker ps
#        - sudo mvn failsafe:integration-test
#      after_script:
#        - sudo docker ps | xargs sudo docker rm -f
    - stage: integration
      name: "Fabric8 docker-maven-plugin"
      script:
        - sudo mvn docker:build
        - sudo mvn verify
    - stage: deploy
      name: "Deploy to DockerHub"
      script: 
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - mvn docker:build
        - mvn docker:push
