dist: bionic
sudo: required
env:
  global:
  - TAG="$(git log -1 --pretty=%h)"
  - FOREMAN_RELEASE=1.20
  - PUPPET_VERSION=6.5.0
  - R10K_VERSION=3.3.1
  - UBUNTU_CODENAME=bionic
  - secure: elEmEa4y/Z71ghvMD/582rkoChBjz4OYtELwjNeGu3yiMsaVhOleb8OUGIa5wAi1DgKRLcRHXVIRH2JZLXhXY92F9zeSV7kOY0FuFmIHdVlo2Gs3DF1xCfgkvijHX3SFtAcxyMq8OQlKFNmYvuwcGq2dhlYCC5BlmEgmSH0VPoFc2pvKiZ4aILH3oTeJu631KUIOjM1Xnrt0ZNRT+jodc3koWpKNoTMBGdfm4mdvwUEFUxPcAEehoTsdeYTZWW/4uwajBI0hA6n1wRdjqGcEWbKarWC3JX1zeaNLHxXKMmum0SdlnP0QDjy1ROlGPzy351EEP7drZ41tByMZaRpwNQhy8oVtBscCaeYuRUjkuRltChEWWKyX/yl6XA92Z8GDZgnu1gglJbaZljX+xJlOt8kktAg1qF0jMiHdunWYX2MlCXt5Jpc/bvpo3Yu/w2YelQ2gZVXqsVJ/l0M69Jm4QGSocjy9/Vs/UbT7wthXFlfBeFD/ME9KrQYe4NjHKWv38m7RdX/9KAsDvR/i3uZHxyvPLvy6g/VcRfSvAtk7Sb/KfZLEs974p+tHQ3qMQSyczx9b72tvKgNTlFwgu+00WY4UPmQ9lQ1GXG6WLmbDZF4OwYsD0Hu6Wy3zS6evPlQlsEnVTu4VQ6uFyfCX+VFDJzFFS3tGdUGTU1bHUPJuqLc=
  - secure: TvrkxzeJBVL5UuWl0mItqWVZYFbnb8aA0BO63KyEwPT9fbWGRUMZJKJJkLa7KRykftgXkkvmj/LIaT4z1lhenWFXdXSDEfDvzU4/vPhD0Do2GS6Pkj28NhXxfPf4xv2hZyqNv00BshRJZq/iXBR6Yeduh4izk1z/khDaOum98k+mfaZ/AQeiGpGiRO5GzRsyMGrRnplunVHiQvKs+b22gB0MHc7JSAgvmvWZNv99zv+m1S8rnWwMYemOq3omSvjTE1mH4DgP5Yc+zORZykQPausvoARtYfX8FUBBki83Atdrlj1KKeBR8duGCisL2XVhNkrJVZl6EBRXaeEHyVqL7AyUYmybUD6YRmRbAxnSr8iSRtgmO4qrLRCoDjprzd3wikgo1BV2bAhjUtfCaO5L4Z5pHYyPrJYEeDM1dTEfy++hHC7V1U/AM4sjHkyGkgntTJ2b78A071I72epEkBuDN4WjXYy3IDH6qF8qBbqq5VqnzQdD3/gDXjms44wnzuPKr7xB8Fh2h2uHBqR08HAYvET5DVIoVp1dd4IgZso+BzAiiy5656dPcgTSs05TcY1ckYZwe+Adqu2R9OCifOd8Y+qEeBUWAJzmWLvi/TAZRyqqUzgeJi5UyW4zrLS8sDbC+ERaaHDjrQmevoKyidz50jUrmHk36gGEkyKrOYFzBr4=
stages:
- syntax
- build
- integration
- name: deploy
  if: branch = master
services:
- docker
jobs:
  include:
  - stage: syntax
    name: Hadolint
    script:
    - docker run --rm -i hadolint/hadolint < src/main/images/foreman/Dockerfile
    - docker run --rm -i hadolint/hadolint < src/main/images/puppet/Dockerfile
    - docker run --rm -i hadolint/hadolint < src/main/images/puppet-smart-proxy/Dockerfile
  - name: Shellchecker
    script: docker run --rm -v "$(pwd)":/mnt koalaman/shellcheck:stable src/main/images/foreman/*.sh
  - stage: build
    name: Build Puppet, Foreman, Foreman Puppet smart proxy, and R10k images
    script:
    - cd $TRAVIS_BUILD_DIR/images/puppetserver
    - docker build -t luksi1/puppetserver-docker:${TAG} .
    - cd $TRAVIS_BUILD_DIR/images/foreman
    - docker build --build-arg FOREMAN_RELEASE=${FOREMAN_RELEASE} -t luksi1/foreman:${TAG} .
    - cd $TRAVIS_BUILD_DIR/images/puppet-smart-proxy
    - docker build --build-arg FOREMAN_RELEASE=${FOREMAN_RELEASE} -t luksi1/puppet-smart-proxy:${TAG} .
    - cd $TRAVIS_BUILD_DIR/images/r10k
    - docker build --build-arg R10K_VERSION=${R10K_VERSION} -t luksi1/r10k:${TAG} .
    after_success:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push luksi1/puppetserver-docker:${TAG}
    - docker push luksi1/foreman:${TAG}
    - docker push luksi1/puppet-smart-proxy:${TAG}
    - docker push luksi1/r10k:${TAG}
  - stage: integration
    name: docker-compose
    addons:
      apt:
        sources:
        - sourceline: 'deb http://apt.puppetlabs.com bionic puppet6'
          key_url: 'https://apt.puppetlabs.com/DEB-GPG-KEY-puppet'
        - sourceline: 'deb https://deb.nodesource.com/node_10.x stretch main'
          key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
        packages:
        - puppetserver
        - openssl
        - nodejs
        - curl
        - gnupg
    env:
    - DOCKER_COMPOSE_VERSION=1.23.1
    - DOCKER_HOST=tcp://127.0.0.1:2375
    - UBUNTU_VERSION=bionic
    - PUPPETSERVER_URL=puppet.domain.test
    - FOREMAN_URL=foreman.domain.test
    before_install:
    - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname
      -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    # This is bailing with
    # Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0
    # Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
    # Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
    # Traceback (most recent call last):
	  # 2: from /opt/puppetlabs/server/apps/puppetserver/cli/apps/ca:3:in `<main>'
	  # 1: from /opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
    # /opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- puppetserver/ca/cli (LoadError)
    # - sudo /opt/puppetlabs/server/bin/puppetserver ca setup --ca-name puppet.domain.com
    # The following is a workaround
    - sudo docker run -it -v /etc/puppetlabs/puppet/ssl:/etc/puppetlabs/puppet/ssl puppet/puppetserver:latest ca setup --ca-name puppet.domain.com
    - sudo docker run -it -v /etc/puppetlabs/puppet/ssl:/etc/puppetlabs/puppet/ssl puppet/puppetserver:latest ca generate --certname foreman.domain.com || true
    - openssl req -new -newkey rsa:4096 -days 1 -nodes -x509 -subj "/C=SE/L=Gothenburg/CN=${FOREMAN_URL}" -keyout /tmp/foreman.key -out /tmp/foreman.crt
    install:
    - npm install newman
    - cd examples/docker-compose
    - sudo docker-compose up -d
    - sleep 180
    script:
    - cd $TRAVIS_BUILD_DIR
    - node_modules/.bin/newman run tests/foreman.json --insecure
    after_script:
    - docker-compose stop
    - docker-compose rm -f
  - stage: deploy
    name: Deploy to DockerHub
    script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - mvn docker:build
    - mvn docker:push