dist: bionic
os: linux
language: ruby
env:
  global:
  - TAG="$(git log -1 --pretty=%h)"
  - FOREMAN_RELEASE=1.20
  - PUPPET_VERSION=6.5.0
  - R10K_VERSION=3.3.1
  - UBUNTU_CODENAME=bionic
  - secure: elEmEa4y/Z71ghvMD/582rkoChBjz4OYtELwjNeGu3yiMsaVhOleb8OUGIa5wAi1DgKRLcRHXVIRH2JZLXhXY92F9zeSV7kOY0FuFmIHdVlo2Gs3DF1xCfgkvijHX3SFtAcxyMq8OQlKFNmYvuwcGq2dhlYCC5BlmEgmSH0VPoFc2pvKiZ4aILH3oTeJu631KUIOjM1Xnrt0ZNRT+jodc3koWpKNoTMBGdfm4mdvwUEFUxPcAEehoTsdeYTZWW/4uwajBI0hA6n1wRdjqGcEWbKarWC3JX1zeaNLHxXKMmum0SdlnP0QDjy1ROlGPzy351EEP7drZ41tByMZaRpwNQhy8oVtBscCaeYuRUjkuRltChEWWKyX/yl6XA92Z8GDZgnu1gglJbaZljX+xJlOt8kktAg1qF0jMiHdunWYX2MlCXt5Jpc/bvpo3Yu/w2YelQ2gZVXqsVJ/l0M69Jm4QGSocjy9/Vs/UbT7wthXFlfBeFD/ME9KrQYe4NjHKWv38m7RdX/9KAsDvR/i3uZHxyvPLvy6g/VcRfSvAtk7Sb/KfZLEs974p+tHQ3qMQSyczx9b72tvKgNTlFwgu+00WY4UPmQ9lQ1GXG6WLmbDZF4OwYsD0Hu6Wy3zS6evPlQlsEnVTu4VQ6uFyfCX+VFDJzFFS3tGdUGTU1bHUPJuqLc=
  - secure: TvrkxzeJBVL5UuWl0mItqWVZYFbnb8aA0BO63KyEwPT9fbWGRUMZJKJJkLa7KRykftgXkkvmj/LIaT4z1lhenWFXdXSDEfDvzU4/vPhD0Do2GS6Pkj28NhXxfPf4xv2hZyqNv00BshRJZq/iXBR6Yeduh4izk1z/khDaOum98k+mfaZ/AQeiGpGiRO5GzRsyMGrRnplunVHiQvKs+b22gB0MHc7JSAgvmvWZNv99zv+m1S8rnWwMYemOq3omSvjTE1mH4DgP5Yc+zORZykQPausvoARtYfX8FUBBki83Atdrlj1KKeBR8duGCisL2XVhNkrJVZl6EBRXaeEHyVqL7AyUYmybUD6YRmRbAxnSr8iSRtgmO4qrLRCoDjprzd3wikgo1BV2bAhjUtfCaO5L4Z5pHYyPrJYEeDM1dTEfy++hHC7V1U/AM4sjHkyGkgntTJ2b78A071I72epEkBuDN4WjXYy3IDH6qF8qBbqq5VqnzQdD3/gDXjms44wnzuPKr7xB8Fh2h2uHBqR08HAYvET5DVIoVp1dd4IgZso+BzAiiy5656dPcgTSs05TcY1ckYZwe+Adqu2R9OCifOd8Y+qEeBUWAJzmWLvi/TAZRyqqUzgeJi5UyW4zrLS8sDbC+ERaaHDjrQmevoKyidz50jUrmHk36gGEkyKrOYFzBr4=
stages:
- syntax
- build
- integration
- name: deploy
  if: branch = master
services:
- docker
matrix:
  include:
  - stage: syntax
    name: Hadolint
    script:
    - docker run --rm -i hadolint/hadolint < images/foreman/Dockerfile
    - docker run --rm -i hadolint/hadolint < images/puppetserver/Dockerfile
    - docker run --rm -i hadolint/hadolint < images/puppet-smart-proxy/Dockerfile
  - name: Shellchecker
    script: docker run --rm -v "$(pwd)":/mnt koalaman/shellcheck:stable images/foreman/*.sh
  - stage: build
    name: Build Puppet, Foreman, Foreman Puppet smart proxy, and R10k images
    script:
    - cd $TRAVIS_BUILD_DIR/images/puppetserver
    - docker build -t luksi1/puppetserver-foreman:${TAG} .
    - cd $TRAVIS_BUILD_DIR/images/foreman
    - docker build --build-arg FOREMAN_RELEASE=${FOREMAN_RELEASE} -t luksi1/foreman:${TAG} .
    - cd $TRAVIS_BUILD_DIR/images/puppet-smart-proxy
    - docker build --build-arg FOREMAN_RELEASE=${FOREMAN_RELEASE} -t luksi1/puppet-smart-proxy:${TAG} .
    - cd $TRAVIS_BUILD_DIR/images/r10k
    - docker build --build-arg R10K_VERSION=${R10K_VERSION} -t luksi1/r10k:${TAG} .
    after_success:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push luksi1/puppetserver-foreman:${TAG}
    - docker push luksi1/foreman:${TAG}
    - docker push luksi1/puppet-smart-proxy:${TAG}
    - docker push luksi1/r10k:${TAG}
  - stage: integration
    name: docker-compose
    addons:
      apt:
        sources:
        - sourceline: 'deb https://deb.nodesource.com/node_10.x stretch main'
          key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
        packages:
        - openssl
        - nodejs
        - curl
        - gnupg
        - python3
    env:
    - DOCKER_COMPOSE_VERSION=1.23.1
    - UBUNTU_VERSION=bionic
    - PUPPETSERVER_URL=puppet.dummy.test
    - FOREMAN_URL=foreman.dummy.test
    before_install:
    # install docker-compose
    - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname
      -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - scripts/create.certificates.sh
    install:
    - npm install newman
    - cd examples/docker-compose
    - sudo -E docker-compose up -d
    # Wait for 3 minutes while docker-compose boots up
    - i=0 && while [ $i -lt 180 ]; do sleep 1; echo -n "."; i=$[$i+1]; done
    script:
    # grab password from foreman
    - FOREMAN_CONTAINER_ID=$(/usr/bin/sudo /usr/bin/docker ps -qaf label=org.label-schema.name=foreman)
    - ADMIN_PASSWORD=$(/usr/bin/sudo /usr/bin/docker exec -t $FOREMAN_CONTAINER_ID foreman-rake permissions:reset | /bin/grep 'Reset to user:' | /usr/bin/awk '{print $NF}' | xargs echo -n)
    - cd $TRAVIS_BUILD_DIR
    # swap out admin password
    - echo $ADMIN_PASSWORD
    - /usr/bin/perl -i -pe "s/2T4pNTKJTBU3ujmb/${ADMIN_PASSWORD}/g" tests/foreman.json
    - cat tests/foreman.json
    # validate json
    - /usr/bin/python3 -m json.tool < tests/foreman.json
    # perform tests
    - node_modules/.bin/newman run tests/foreman.json --insecure
    after_script:
    - docker-compose stop
    - docker-compose rm -f
  - stage: deploy
    name: Deploy to DockerHub
    script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - mvn docker:build
    - mvn docker:push

