---
language: node_js
node_js:
  - "8.2.1"

sudo: required

env:
  global: 
    - TAG="$(date -Is)-$(git log -1 --pretty=%h)"

stages:
  - syntax
  - build
  - integration
  - name: deploy
    if: branch = master

services:
  - docker

before_install:
  - sudo apt-get update && sudo apt-get install -y openssl maven openjdk-8-jdk

jobs:
  include:
    - stage: syntax
      name: "Hadolint"
      script:
        - docker run --rm -i hadolint/hadolint < src/main/images/foreman/Dockerfile
        - docker run --rm -i hadolint/hadolint < src/main/images/puppet/Dockerfile
    -
      name: "Shellchecker"
      script: docker run --rm -v "$(pwd)":/mnt koalaman/shellcheck:stable src/main/images/foreman/*.sh
    - stage: build
      before_script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      name: "Build Puppet image"
      script:
        - cd images/puppetserver
        - docker build -t luksi1/puppetserver-docker:${TAG} .
        - docker push luksi1/puppetserver-docker:${TAG}
    -
      name: "Build Foreman image"
      script:
        - cd images/foreman
        - docker build -t luksi1/foreman:${TAG}
        - docker push luksi1/foreman:${TAG}
    -
      name: "Build Foreman Puppet Smart Proxy image"
      script:
        - cd images/puppet-smart-proxy
        - docker build -t luksi1/puppet-smart-proxy:${TAG}
        - docker push luksi1/puppet-smart-proxy:${TAG}
    -
      name: "Build R10K"
      script:
        - cd images/r10k
        - docker build -t luksi1/r10k:${TAG}
        - docker push luksi1/r10k:${TAG}
    - stage: integration
      name: "docker-compose"
      env:
        - DOCKER_COMPOSE_VERSION=1.23.1
        - DOCKER_HOST=tcp://127.0.0.1:2375
        - UBUNTU_VERSION=bionic
        - PUPPETSERVER_URL=puppet.domain.test
        - FOREMAN_URL=foreman.domain.test
      before_install:
        - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
        - wget https://apt.puppetlabs.com/puppetlabs-release-${UBUNTU_VERSION}.deb
        - sudo dpkg -i puppetlabs-release-${UBUNTU_VERSION}.deb
        - sudo apt-get update
        - sudo apt-get install puppetserver
        - sudo puppetserver ca setup --ca-name puppet.domain.com
        # Allow this to fail, since we haven't started our puppetserver yet, the API call in the end will fail
        # But we simply need to get the public/private keys
        - sudo puppetserver ca generate  --certname foreman.domain.com || true
        - openssl req -new -newkey rsa:4096 -days 1 -nodes -x509 -subj "/C=SE/L=Gothenburg/CN=${FOREMAN_URL}" -keyout /tmp/foreman.key -out /tmp/foreman.crt
      install:
        - npm install newman
        - cd examples/docker-compose
        - sudo docker-compose up -d
        - sleep 180
      script:
        - cd $TRAVIS_BUILD_DIR
        - node_modules/.bin/newman run tests/foreman.json --insecure
      after_script:
        - docker-compose stop
        - docker-compose rm -f
    - stage: deploy
      name: "Deploy to DockerHub"
      script: 
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - mvn docker:build
        - mvn docker:push
