version: "3.2"
services:
  puppetdb-postgres:
    container_name: puppetdb-postgres
    hostname: postgres
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: puppetdb
      POSTGRES_USER: puppetdb
      POSTGRES_DB: puppetdb
    ports:
      - 5432
    volumes:
      - /databases/puppetdb-postgres:/var/lib/postgresql/data/
    networks:
      puppet-foreman-network:
        aliases:
          - puppetdb-postgres
          - postgres
  foreman-postgres:
    container_name: foreman-postgres
    image: postgres:9.6
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 'foreman'
      POSTGRES_USER: 'foreman'
      POSTGRES_DB: 'foreman'
    volumes:
      - /databases/foreman-postgres:/var/lib/postgresql/data/
    networks:
      puppet-foreman-network:
        aliases:
          - foreman-postgres
  puppetserver:
    container_name: puppetserver
    hostname: ${puppetserver_hostname}
    domainname: ${domain}
    image: luksi1/puppetserver-foreman:${PUPPETSERVER_TAG:-6.7.1}
    ports:
      - "8140:8140"
    environment:
      PUPPETSERVER_HOSTNAME: ${puppetserver_hostname}.${domain}
      FOREMAN_HOSTNAME: ${foreman_hostname}.${domain}
      FOREMAN_WEB_CA_CERTIFICATE: /etc/puppetlabs/foreman/ssl/ca.pem
    volumes:
      - /etc/puppetlabs/code:/etc/puppetlabs/code/
      - /opt/puppetlabs/server/data/puppetserver/:/opt/puppetlabs/server/data/puppetserver/
      - ${foreman_server_cert_chain_file}:/etc/puppetlabs/foreman/ssl/ca.pem
      - /etc/puppetlabs/puppet/ssl/crl.pem:/etc/puppetlabs/puppet/ssl/crl.pem
      - /etc/puppetlabs/puppet/ssl/ca/:/etc/puppetlabs/puppet/ssl/ca/
      - /etc/puppetlabs/puppet/ssl/certificate_requests/:/etc/puppetlabs/puppet/ssl/certificate_requests/
      - /etc/puppetlabs/puppet/ssl/private/:/etc/puppetlabs/puppet/ssl/private/
      - /etc/puppetlabs/puppet/ssl/private_keys/:/etc/puppetlabs/puppet/ssl/private_keys/
      - /etc/puppetlabs/puppet/ssl/public_keys/:/etc/puppetlabs/puppet/ssl/public_keys/
      - /etc/puppetlabs/puppet/ssl/certs/${puppetserver_hostname}.${domain}.pem:/etc/puppetlabs/puppet/ssl/certs/${puppetserver_hostname}.${domain}.pem
      - /etc/puppetlabs/puppet/ssl/certs/ca.pem:/etc/puppetlabs/puppet/ssl/certs/ca.pem
    networks:
      puppet-foreman-network:
        aliases:
          - ${puppetserver_hostname}
          - ${puppetserver_hostname}.${domain}
  puppetdb:
    container_name: puppetdb
    hostname: puppetdb
    image: puppet/puppetdb:latest
    ports:
      - "8081:8080"
      - "8080:8080"
    environment:
      - PUPPETDB_POSTGRES_HOSTNAME=puppetdb-postgres
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
      - USE_PUPPETSERVER='false'
    volumes:
      - /etc/puppetlabs/puppet/ssl/:/etc/puppetlabs/puppet/ssl/
    networks:
      puppet-foreman-network:
        aliases:
          - puppetdb
  foreman:
    container_name: foreman
    command: bundle exec bin/rails server -b 0.0.0.0
    hostname: ${foreman_hostname}.${domain}
    # image: luksi1/foreman:${FOREMAN_TAG:-5034970}
    image: quay.io/foreman/foreman:1.23-stable
    ports:
    - "3000:3000"
    - "5910-5930:5910-5930"
    environment:
    - DATABASE_URL=postgres://foreman:foreman@foreman-postgres:5432/foreman?pool=5
    - RAILS_MAX_THREADS=5
    - RAILS_ENV=development
    - FOREMAN_FQDN=${foreman_hostname}.${domain}
    - FOREMAN_DOMAIN=${domain}
    - FOREMAN_RAILS_CACHE_STORE_TYPE=redis
    - FOREMAN_RAILS_CACHE_STORE_URLS=redis://redis:6379/0
    # volumes:
    # - ${foreman_server_cert_file}:/certs/server.crt
    # - ${foreman_server_cert_key_file}:/certs/server.key
    # - ${foreman_server_cert_chain_file}:/certs/server_cachain.pem
    # - /etc/puppetlabs/puppet/ssl/certs/ca.pem:/certs/client_ca.pem
    # - /etc/puppetlabs/puppet/ssl/ca/ca_crl.pem:/certs/client_crl.pem
    # - /etc/puppetlabs/puppet/ssl/certs/${foreman_hostname}.${domain}.pem:/certs/client.crt
    # - /etc/puppetlabs/puppet/ssl/private_keys/${foreman_hostname}.${domain}.pem:/certs/client.key
    networks:
      puppet-foreman-network:
        aliases:
        - ${foreman_hostname}
        - ${foreman_hostname}.${domain}
  worker:
    command: bundle exec rake dynflow:executor
    container_name: worker
    image: quay.io/foreman/foreman:1.23-stable
    hostname: worker.${domain}
    command: bundle exec rake dynflow:executor
    environment:
    - DATABASE_URL=postgres://foreman:foreman@foreman-postgres:5432/foreman?pool=5
    - RAILS_MAX_THREADS=5
    - RAILS_ENV=development
    - FOREMAN_FQDN=${foreman_hostname}.${domain}
    - FOREMAN_DOMAIN=${domain}
    - FOREMAN_RAILS_CACHE_STORE_TYPE=redis
    - FOREMAN_RAILS_CACHE_STORE_URLS=redis://redis:6379/0
    ports:
      - 9999
    networks:
      puppet-foreman-network:
        aliases:
        - worker
        - worker.${domain}
  puppet-smart-proxy:
    container_name: puppet-smart-proxy
    image: luksi1/puppet-smart-proxy:${PUPPET_SMART_PROXY_TAG:-5034970}
    environment:
      TRUSTED_HOSTS: "${foreman_hostname},${foreman_hostname}.${domain},${puppetserver_hostname},${puppetserver_hostname}.${domain}"
      PUPPET_VERSION: "${puppetserver_version}"
      PUPPET_URL: "https://${puppetserver_hostname}.${domain}:8140"
      FOREMAN_URL: "https://${foreman_hostname}.${domain}"
    volumes:
    - /etc/puppetlabs/puppet/ssl/certs/${puppet_smartproxy_hostname}.${domain}.pem:/certs/public.crt
    - /etc/puppetlabs/puppet/ssl/private_keys/${puppet_smartproxy_hostname}.${domain}.pem:/certs/private.key
    - /etc/puppetlabs/puppet/ssl/certs/ca.pem:/certs/ca.pem
    networks:
      puppet-foreman-network:
        aliases:
        - puppet-smart-proxy
        - puppet-smart-proxy.${domain}
  r10k:
    container_name: r10k
    image: luksi1/r10k:${R10K_TAG:-5034970}
    ports:
    - "8088:8088"
    environment:
      CONTROL_REPO: ${control_repo}
    volumes:
    - /etc/puppetlabs/code:/etc/puppetlabs/code
    networks:
      puppet-foreman-network:
        aliases:
        - r10k
  redis:
    image: redis
    container_name: redis
    networks:
      puppet-foreman-network:
        aliases:
        - redis
networks:
  puppet-foreman-network:
    driver: bridge